import "@/styles/globals.css"
import {QuizSearch} from "@/modules/Quiz";
import {ProfilePhoto} from "@/modules/User";
import Image from "next/image";
import React from "react";
import TextInput from "@/components/input/TextInput";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
            <header className="app-header">
                <div className="container mx-auto px-4">
                    <nav className="flex items-center justify-between">
                        <div>
                            <Image src="/ts-icon.png" alt="icon" width={185} height={50}/>
                        </div>

                        <div className="flex justify-between">
                            <QuizSearch />

                            <ProfilePhoto />
                        </div>
                    </nav>
                </div>
            </header>
            <div className='container mx-auto px-4 py-8 mt-8'>
                {children}
            </div>
        </body>
        </html>
    )
}
