import "@/styles/globals.css"
import {QuizSearch} from "@/modules/Quiz";
import {ProfilePhoto} from "@/modules/User";
import React from "react";
import Link from "next/link";
import Logo from "@/components/Logo";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
            <header className="app-header">
                <div className="container mx-auto px-4">
                    <nav className="flex items-center justify-between">

                        <Logo url='/' />

                        <div className="flex gap-8 justify-between">
                            <Link href='/' className="link pt-3">
                                Home
                            </Link>

                            <Link href='/quiz/create' className='link pt-3'>
                                Create Quiz
                            </Link>

                            <QuizSearch />

                            <ProfilePhoto />
                        </div>
                    </nav>
                </div>
            </header>
            <div className='container mx-auto px-4 py-8 mt-8'>
                {children}
            </div>
        </body>
        </html>
    )
}
